# For the lazy:
# Build: docker compose -f .\dev.docker-compose.yml build --no-cache
# Run: docker compose -f .\dev.docker-compose.yml up

version: '3.1'

name: bitorch-development

services:
  peer0:
    container_name: peer0
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .docker.env
    environment:
      - PEER_NAME=peer0
      - BACKEND_PORT=8000
    stdin_open: true
    tty: true

  peer1:
    container_name: peer1
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .docker.env
    environment:
      - PEER_NAME=peer1
      - BACKEND_PORT=8001
    stdin_open: true
    tty: true

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"

networks:
  default:
    driver: bridge
