# For the lazy:
# Build: docker compose -f .\dev.docker-compose.yml build --no-cache
# Run: docker compose -f .\dev.docker-compose.yml up

version: '3.1'

name: bitorch-development

services:
  node0:
    container_name: node0
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    stdin_open: true
    tty: true
  node1:
    container_name: node1
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    stdin_open: true
    tty: true

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"

networks:
  default:
    driver: bridge
