# For the lazy:
# Build: docker compose -f .\dev.docker-compose.yml build --no-cache
# Run: docker compose -f .\dev.docker-compose.yml up
# Run with watch: docker compose -f .\dev.docker-compose.yml watch
# ^ Watches the local directory for changes and updates all containers without killing them.

version: '3.1'

name: bitorch-development

services:
  peer0:
    container_name: peer0
    command: /bin/sh -c "env && pipenv run python run.py"
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PEER_NAME=peer0
      - BACKEND_PORT=8000
      # Set db here so that we can simulate multiple nodes with a single mongodb container with their own db's:
      - DB_NAME=peer0
      - MONGO_URL=mongodb://mongodb:27017/
    stdin_open: true
    tty: true
    depends_on:
      - mongodb
  
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - "27017:27017"
